# Site settings
plugins:
  - jekyll-feed
title: "Grant Isom"
description: >
  Software Engineer from Kansas City.
  Writing mainly about iOS and Web Development.

author: Grant Isom
email: grant.isom@gmail.com
linkedin_username: grantisom
github_username: glisom

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grantisom.com" # the base hostname & protocol for your site

google_analytics_id: UA-49331805-1

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]
