# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Grant Isom
email: grant.isom@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Computer Science student at the University of Kansas, SELF
    Fellow, Member of the Catalyst Entrepreneurship Program, Mobile/Web Software Developer,
    and Entrepreneur
baseurl: "" # the subpath of your site, e.g. /blog
url: "grantisom.com" # the base hostname & protocol for your site
twitter_username: grantisom
github_username:  glisom

# Build settings
markdown: kramdown
