# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Grant L. Isom
paginate:       5
baseurl:        ""
url:            "http://grantisom.com"
google_analytics: UA-49331805-1

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Grant Isom
  url:          http://grantisom.com
  email:        grant.isom@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/glisom/glisom.github.io

# Gems
plugins:
  - jekyll-paginate
