# Site settings
title: "Grant Isom"
description: >
  Write a description of your website here.

author: Grant Isom
email: grant.isom@gmail.com
twitter_username: grantisom
github_username: glisom

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grantisom.com" # the base hostname & protocol for your site

google_analytics_id: UA-49331805-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]
