# Site settings
plugins:
  - jekyll-feed
title: "Grant Isom"
description: >
  👋 Hi, I'm Grant.

author: Grant Isom
email: grant.isom@gmail.com
linkedin_username: grantisom
github_username: glisom

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grantisom.com" # the base hostname & protocol for your site

# Build settings
include: [_pages]
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:year/:month/:day/:title.html

sass:
  style: compressed

exclude: [vendor]
